export const SET_TV_SHOW = 'SET_TV_SHOW';
export const SET_SIMILAR_TV_SHOW = 'SET_SIMILAR_TV_SHOW';
export const SET_RATINGS_FROM_SITES = 'SET_RATINGS_FROM_SITES';
export const FETCH_SHOW_START = 'FETCH_SHOW_START';
export const FETCH_SHOW_SUCCESS = 'FETCH_SHOW_SUCCESS';
export const FETCH_SHOW_FAILED = 'FETCH_SHOW_FAILED';
export const SET_ERROR = 'SET_ERROR';